agentName: agent002
envName: dev
agentRuntimeName: agent002_dev
imageRepo: 229560443702.dkr.ecr.us-west-2.amazonaws.com
tag: 0.0.0
roleArn: arn:aws:iam::229560443702:role/service-role/AmazonBedrockAgentCoreRuntimeDefaultServiceRole

environmentVariables:
  # TENANT_SECRETS_PATH: "tenant01/agent001_dev"
  # REGION: "us-west-2"
